# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='full_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='phone',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='gender',
        ),
    ]
